var DEBUG=!1,MessageDecoder=function(l){this._SP_ENCRYPT_OX_CONST=538185768;this._MSG_HEADER_LEN=4;this._LITTLE_ENDIAN=!0;this._BYTE_ALIGNED=4;this._SUPPORT_DATATYPE={CHAR:1,INT8:1,UINT8:1,INT16:1,UINT16:1,INT32:1,UINT32:1,UINT64:1,INT64:1,BOOL:1,FLOAT:1,DOUBLE:1,STRUCT:1,STRUCT_ARRAY:2,INT8_ARRAY:2,UINT8_ARRAY:2,INT16_ARRAY:2,UINT16_ARRAY:2,INT32_ARRAY:2,UINT32_ARRAY:2,UINT64_ARRAY:2,INT64_ARRAY:2,BOOL_ARRAY:2,FLOAT_ARRAY:2,DOUBLE_ARRAY:2,STRING:2};if(l)this._bigVer=l.getBigVer(),this._littleVer=
l.getLittleVer(),this._dataStruct=l.getDataStruct(),this._heartBeatCode=l.getHeartBeatCode();else return console.error("typeDef is null"),null};MessageDecoder.prototype._SPEncrypt2_0_Encrypt=function(l){for(var b=l.byteLength,c=b>>2,f=new DataView(l),k=0;k<c;++k){var a=f.getUint32(4*k,this._LITTLE_ENDIAN);a^=this._SP_ENCRYPT_OX_CONST;f.setUint32(4*k,a,this._LITTLE_ENDIAN)}for(k=0;k<b;++k)a=f.getUint8(k),a=~a,f.setUint8(k,a);return l};
MessageDecoder.prototype._SPEncrypt2_0_Decode=function(l){for(var b=l.byteLength,c=b>>2,f=new DataView(l),k=0;k<b;++k){var a=f.getUint8(k);a=~a;f.setUint8(k,a)}for(k=0;k<c;++k)a=f.getUint32(4*k,this._LITTLE_ENDIAN),a^=this._SP_ENCRYPT_OX_CONST,f.setUint32(4*k,a,this._LITTLE_ENDIAN);return l};
MessageDecoder.prototype._GenHeader=function(l){var b=new ArrayBuffer(this._MSG_HEADER_LEN),c=new DataView(b);c.setUint8(0,this._bigVer);c.setUint8(1,this._littleVer);l=parseInt(l.substr(2),16);c.setUint16(2,l,this._LITTLE_ENDIAN);return b};
MessageDecoder.prototype._GetBodyLen=function(l){var b=0,c=1,f=l.DONT_FILL_PLACE?!1:!0,k;for(k in l)if("DONT_FILL_PLACE"!=k){var a=l[k];if(!this._SUPPORT_DATATYPE[a.type])return console.error(k+".type not support "),0;if(2==this._SUPPORT_DATATYPE[a.type]&&"number"!=typeof a.length)return console.error(k+".length is not number"),0;if("CHAR"==a.type||"BOOL"==a.type||"INT8"==a.type||"UINT8"==a.type)b+=1;else if("STRING"==a.type||"BOOL_ARRAY"==a.type||"INT8_ARRAY"==a.type||"UINT8_ARRAY"==a.type)a.length&&
(b+=a.length);else if("INT16"==a.type||"UINT16"==a.type)f&&(b+=b%2,2>c&&(c=2)),b+=2;else if("INT16_ARRAY"==a.type||"UINT16_ARRAY"==a.type)f&&a.length&&(b+=b%2,2>c&&(c=2)),b+=2*a.length;else if("INT32"==a.type||"UINT32"==a.type||"FLOAT"==a.type)f&&(0<b%4&&(b+=4-b%4),4>c&&(c=4)),b+=4;else if("INT32_ARRAY"==a.type||"UINT32_ARRAY"==a.type||"FLOAT_ARRAY"==a.type)f&&(0<b%4&&(b+=4-b%4),4>c&&(c=4)),b+=4*a.length;else if("UINT64"==a.type||"INT64"==a.type||"DOUBLE"==a.type)f&&(0<b%this._BYTE_ALIGNED&&(b+=this._BYTE_ALIGNED-
b%this._BYTE_ALIGNED),c=this._BYTE_ALIGNED),b+=8;else if("UINT64_ARRAY"==a.type||"INT64_ARRAY"==a.type||"DOUBLE_ARRAY"==a.type)f&&0<b%this._BYTE_ALIGNED&&(b+=this._BYTE_ALIGNED-b%this._BYTE_ALIGNED),b+=8*a.length;else if("STRUCT"==a.type){if(!this._dataStruct[a.structName])return console.warn("message definitions not found:"+a.structName),null;var e=this._GetBodyLen(this._dataStruct[a.structName]);f&&0<b%e.maxBaseDataLen&&(b+=e.maxBaseDataLen-b%e.maxBaseDataLen);b+=e.len}else if("STRUCT_ARRAY"==a.type){if(!this._dataStruct[a.structName])return console.warn("message definitions not found:"+
a.structName),null;e=this._GetBodyLen(this._dataStruct[a.structName]);f&&0<b%e.maxBaseDataLen&&(b+=e.maxBaseDataLen-b%e.maxBaseDataLen);b+=a.length*e.len}}f&&(c>this._BYTE_ALIGNED&&(c=this._BYTE_ALIGNED),0<b%c&&(b+=c-b%c));return{len:b,maxBaseDataLen:c}};MessageDecoder.prototype._EncodeUTF8=function(l){l=encodeURIComponent(l);for(var b=[],c=0;c<l.length;c++){var f=l.charAt(c);"%"===f?(f=l.charAt(c+1)+l.charAt(c+2),f=parseInt(f,16),b.push(f),c+=2):b.push(f.charCodeAt(0))}return b};
MessageDecoder.prototype._DecodeUTF8=function(l){for(var b="",c=0;c<l.length;c++)b+="%"+l[c].toString(16);return decodeURIComponent(b)};
MessageDecoder.prototype._GenBody=function(l,b){var c=this._GetBodyLen(l);if(0==c.len)return null;var f=l.DONT_FILL_PLACE?!1:!0;c=new ArrayBuffer(c.len);if(b){var k=new DataView(c),a=0,e;for(e in l)if("DONT_FILL_PLACE"!=e){var g=l[e];if("CHAR"==g.type)b[e]&&k.setUint8(a,b[e].charCodeAt(0)),a+=1;else if("STRING"==g.type){if(b[e])for(var h=this._EncodeUTF8(b[e]),d=0;d<g.length;d++)h[d]&&k.setUint8(a+d,h[d]);a+=g.length}else if("BOOL"==g.type)b[e]&&k.setUint8(a,b[e]),a+=1;else if("BOOL_ARRAY"==g.type){if(b[e])for(h=
b[e],d=0;d<g.length;d++)h[d]&&k.setUint8(a+d,h[d]);a+=g.length}"INT8"==g.type&&(b[e]&&k.setInt8(a,b[e]),a+=1);if("UINT8"==g.type)b[e]&&k.setUint8(a,b[e]),a+=1;else if("UINT8_ARRAY"==g.type||"INT8_ARRAY"==g.type){if(b[e])for(h=b[e],d=0;d<g.length;d++)h[d]&&("UINT8_ARRAY"==g.type?k.setUint8(a+d,h[d]):k.setInt8(a+d,h[d]));a+=g.length}else if("INT16"==g.type)f&&(a+=a%2),b[e]&&k.setInt16(a,b[e],this._LITTLE_ENDIAN),a+=2;else if("UINT16"==g.type)f&&(a+=a%2),b[e]&&k.setUint16(a+a%2,b[e],this._LITTLE_ENDIAN),
a+=2;else if("INT16_ARRAY"==g.type||"UINT16_ARRAY"==g.type){f&&(a+=a%2);if(b[e])for(h=b[e],d=0;d<g.length;d++)h[d]&&("UINT16_ARRAY"==g.type?k.setUint16(a+2*d,h[d],this._LITTLE_ENDIAN):k.setInt16(a+2*d,h[d],this._LITTLE_ENDIAN));a+=2*g.length}else if("INT32"==g.type)f&&0<a%4&&(a+=4-a%4),b[e]&&k.setInt32(a,b[e],this._LITTLE_ENDIAN),a+=4;else if("UINT32"==g.type)f&&0<a%4&&(a+=4-a%4),b[e]&&k.setUint32(a,b[e],this._LITTLE_ENDIAN),a+=4;else if("INT32_ARRAY"==g.type||"UINT32_ARRAY"==g.type){f&&0<a%4&&(a+=
4-a%4);if(b[e])for(h=b[e],d=0;d<g.length;d++)h[d]&&("UINT32_ARRAY"==g.type?k.setUint32(a+4*d,h[d],this._LITTLE_ENDIAN):k.setInt32(a+4*d,h[d],this._LITTLE_ENDIAN));a+=4*g.length}else if("FLOAT"==g.type)f&&0<a%4&&(a+=4-a%4),b[e]&&k.setFloat32(a,b[e],this._LITTLE_ENDIAN),a+=4;else if("FLOAT_ARRAY"==g.type){f&&0<a%4&&(a+=4-a%4);if(b[e])for(h=b[e],d=0;d<g.length;d++)h[d]&&k.setFloat32(a+4*d,h[d],this._LITTLE_ENDIAN);a+=4*g.length}else if("DOUBLE"==g.type)f&&0<a%this._BYTE_ALIGNED&&(a+=this._BYTE_ALIGNED-
a%this._BYTE_ALIGNED),b[e]&&k.setFloat64(a,b[e],this._LITTLE_ENDIAN),a+=8;else if("DOUBLE_ARRAY"==g.type){f&&0<a%this._BYTE_ALIGNED&&(a+=this._BYTE_ALIGNED-a%this._BYTE_ALIGNED);if(b[e])for(h=b[e],d=0;d<g.length;d++)h[d]&&k.setFloat64(a+8*d,h[d],this._LITTLE_ENDIAN);a+=8*g.length}else if("UINT64"==g.type){f&&0<a%this._BYTE_ALIGNED&&(a+=this._BYTE_ALIGNED-a%this._BYTE_ALIGNED);if(b[e]){var m=Math.pow(2,32),n=Math.floor(b[e]/m),p=b[e]%m;k.setUint32(a,p,this._LITTLE_ENDIAN);k.setUint32(a+4,n,this._LITTLE_ENDIAN)}a+=
8}else if("UINT64_ARRAY"==g.type){f&&0<a%this._BYTE_ALIGNED&&(a+=this._BYTE_ALIGNED-a%this._BYTE_ALIGNED);if(b[e])for(h=b[e],m=Math.pow(2,32),d=0;d<g.length;d++)h[d]&&(n=Math.floor(h[d]/m),p=h[d]%m,k.setUint32(a+8*d,p,this._LITTLE_ENDIAN),k.setUint32(a+4+8*d,n,this._LITTLE_ENDIAN));a+=8*g.length}else if("INT64"==g.type)f&&0<a%this._BYTE_ALIGNED&&(a+=this._BYTE_ALIGNED-a%this._BYTE_ALIGNED),b[e]&&((b[e]>Number.MAX_SAFE_INTEGER||b[e]<Number.MIN_SAFE_INTEGER)&&console.error(b[e]+"\u8d85\u51faJS\u957f\u6574\u578b\u5b89\u5168\u8303\u56f4\uff0c\u7cbe\u5ea6\u5c06\u4e0d\u51c6\u786e\uff0c\u8bf7\u68c0\u67e5\u4e1a\u52a1\u6570\u636e"),
m=Math.pow(2,32),0>b[e]?(p=-b[e],n=~Math.floor(p/m),p=~(p%m)+1,p>=m&&(n+=1)):(n=Math.floor(b[e]/m),p=b[e]%m),k.setUint32(a,p,this._LITTLE_ENDIAN),k.setUint32(a+4,n,this._LITTLE_ENDIAN)),a+=8;else if("INT64_ARRAY"==g.type){f&&0<a%this._BYTE_ALIGNED&&(a+=this._BYTE_ALIGNED-a%this._BYTE_ALIGNED);if(b[e])for(h=b[e],m=Math.pow(2,32),d=0;d<g.length;d++)h[d]&&((h[d]>Number.MAX_SAFE_INTEGER||h[d]<Number.MIN_SAFE_INTEGER)&&console.error(h[d]+"\u8d85\u51faJS\u957f\u6574\u578b\u5b89\u5168\u8303\u56f4\uff0c\u7cbe\u5ea6\u5c06\u4e0d\u51c6\u786e\uff0c\u8bf7\u68c0\u67e5\u4e1a\u52a1\u6570\u636e"),
0>h[d]?(p=-h[d],n=Math.floor(p/m),n=~n,p%=m,p=~p+1,p>=m&&(n+=1)):(n=Math.floor(h[d]/m),p=h[d]%m),k.setUint32(a,p,this._LITTLE_ENDIAN),k.setUint32(a+4,n,this._LITTLE_ENDIAN));a+=8*g.length}else if("STRUCT"==g.type){if(!this._dataStruct[g.structName])return console.warn("message definitions not found:"+g.structName),null;h=this._GetBodyLen(this._dataStruct[g.structName]);f&&0<a%h.maxBaseDataLen&&(a+=h.maxBaseDataLen-a%h.maxBaseDataLen);if(b[e]&&(m=this._GenBody(this._dataStruct[g.structName],b[e])))for(m=
new DataView(m),d=0;d<m.byteLength;d++)k.setUint8(a+d,m.getUint8(d));a+=h.len}else if("STRUCT_ARRAY"==g.type){if(!this._dataStruct[g.structName])return console.warn("message definitions not found:"+g.structName),null;h=this._GetBodyLen(this._dataStruct[g.structName]);f&&0<a%h.maxBaseDataLen&&(a+=h.maxBaseDataLen-len%h.maxBaseDataLen);if(b[e])for(d=0;d<g.length;d++)if(b[e][d]&&(m=this._GenBody(this._dataStruct[g.structName],b[e][d])))for(m=new DataView(m),n=0;n<m.byteLength;n++)k.setUint8(a+h.len*
d+n,m.getUint8(n));a+=h.len*g.length}}}return c};
MessageDecoder.prototype._ParseBody=function(l,b){var c=0,f={},k=l.DONT_FILL_PLACE?!1:!0,a;for(a in l)if("DONT_FILL_PLACE"!=a){var e=l[a];if("CHAR"==e.type)f[a]=String.fromCharCode(b.getUint8(c)),c+=1;else if("STRING"==e.type){for(var g="",h=[],d=0;d<e.length;d++){var m=b.getUint8(c+d);if(0==m)break;h.push(m)}0<h.length&&(g=this._DecodeUTF8(h));f[a]=g;c+=e.length}else if("UINT8"==e.type)f[a]=b.getUint8(c),c+=1;else if("INT8"==e.type)f[a]=b.getInt8(c),c+=1;else if("INT8_ARRAY"==e.type||"UINT8_ARRAY"==
e.type){g=[];for(d=0;d<e.length;d++)g[d]="UINT8_ARRAY"==e.type?b.getUint8(c+d):b.getInt8(c+d);f[a]=g;c+=e.length}else if("BOOL"==e.type)f[a]=b.getUint8(c)?!0:!1,c+=1;else if("BOOL_ARRAY"==e.type){g=[];for(d=0;d<e.length;d++)g[d]=b.getUint8(c+d)?!0:!1;f[a]=g;c+=e.length}else if("INT16"==e.type)k&&(c+=c%2),f[a]=b.getInt16(c,this._LITTLE_ENDIAN),c+=2;else if("UINT16"==e.type)k&&(c+=c%2),f[a]=b.getUint16(c,this._LITTLE_ENDIAN),c+=2;else if("INT16_ARRAY"==e.type||"UINT16_ARRAY"==e.type){k&&(c+=c%2);g=
[];for(d=0;d<e.length;d++)g[d]="UINT16_ARRAY"==e.type?b.getUint16(c+2*d,this._LITTLE_ENDIAN):b.getInt16(c+2*d,this._LITTLE_ENDIAN);f[a]=g;c+=2*e.length}else if("INT32"==e.type)k&&0<c%4&&(c+=4-c%4),f[a]=b.getInt32(c,this._LITTLE_ENDIAN),c+=4;else if("UINT32"==e.type)k&&0<c%4&&(c+=4-c%4),f[a]=b.getUint32(c,this._LITTLE_ENDIAN),c+=4;else if("INT32_ARRAY"==e.type||"UINT32_ARRAY"==e.type){k&&0<c%4&&(c+=4-c%4);g=[];for(d=0;d<e.length;d++)g[d]="UINT32_ARRAY"==e.type?b.getUint32(c+4*d,this._LITTLE_ENDIAN):
b.getInt32(c+4*d,this._LITTLE_ENDIAN);f[a]=g;c+=4*e.length}else if("FLOAT"==e.type)k&&0<c%4&&(c+=4-c%4),f[a]=b.getFloat32(c,this._LITTLE_ENDIAN),c+=4;else if("FLOAT_ARRAY"==e.type){k&&0<c%4&&(c+=4-c%4);g=[];for(d=0;d<e.length;d++)g[d]=b.getFloat32(c+4*d,this._LITTLE_ENDIAN);f[a]=g;c+=4*e.length}else if("DOUBLE"==e.type)k&&0<c%this._BYTE_ALIGNED&&(c+=this._BYTE_ALIGNED-c%this._BYTE_ALIGNED),f[a]=b.getFloat64(c,this._LITTLE_ENDIAN),c+=8;else if("DOUBLE_ARRAY"==e.type){k&&0<c%this._BYTE_ALIGNED&&(c+=
this._BYTE_ALIGNED-c%this._BYTE_ALIGNED);g=[];for(d=0;d<e.length;d++)g[d]=b.getFloat64(c+8*d,this._LITTLE_ENDIAN);f[a]=g;c+=8*e.length}else if("UINT64"==e.type)k&&0<c%this._BYTE_ALIGNED&&(c+=this._BYTE_ALIGNED-c%this._BYTE_ALIGNED),h=b.getUint32(c,this._LITTLE_ENDIAN),m=b.getUint32(c+4,this._LITTLE_ENDIAN),f[a]=m*Math.pow(2,32)+h,f[a]>Number.MAX_SAFE_INTEGER&&console.error(f[a]+"\u8d85\u51faJS\u957f\u6574\u578b\u6700\u5927\u503c\uff0c\u7cbe\u5ea6\u5c06\u4e0d\u51c6\u786e\uff0c\u8bf7\u68c0\u67e5\u4e1a\u52a1\u6570\u636e"),
c+=8;else if("INT64"==e.type){k&&0<c%this._BYTE_ALIGNED&&(c+=this._BYTE_ALIGNED-c%this._BYTE_ALIGNED);h=b.getInt32(c,this._LITTLE_ENDIAN);m=b.getInt32(c+4,this._LITTLE_ENDIAN);var n=Math.pow(2,32);0>m?(m=~m,h=~h,h+=1,h>=n&&(h=0,m+=1),f[a]=-(m*n+h)):f[a]=m*n+h;(f[a]>Number.MAX_SAFE_INTEGER||f[a]<Number.MIN_SAFE_INTEGER)&&console.error(f[a]+"\u8d85\u51faJS\u957f\u6574\u578b\u5b89\u5168\u8303\u56f4\uff0c\u7cbe\u5ea6\u5c06\u4e0d\u51c6\u786e\uff0c\u8bf7\u68c0\u67e5\u4e1a\u52a1\u6570\u636e");c+=8}else if("UINT64_ARRAY"==
e.type){k&&0<c%this._BYTE_ALIGNED&&(c+=this._BYTE_ALIGNED-c%this._BYTE_ALIGNED);g=[];for(d=0;d<e.length;d++)h=b.getUint32(c+8*d,this._LITTLE_ENDIAN),m=b.getUint32(c+4+8*d,this._LITTLE_ENDIAN),g[d]=m*Math.pow(2,32)+h,g[d]>Number.MAX_SAFE_INTEGER&&console.error(g[d]+"\u8d85\u51faJS\u957f\u6574\u578b\u6700\u5927\u503c\uff0c\u7cbe\u5ea6\u5c06\u4e0d\u51c6\u786e\uff0c\u8bf7\u68c0\u67e5\u4e1a\u52a1\u6570\u636e");f[a]=g;c+=8*e.length}else if("INT64_ARRAY"==e.type){k&&0<c%this._BYTE_ALIGNED&&(c+=this._BYTE_ALIGNED-
c%this._BYTE_ALIGNED);g=[];n=Math.pow(2,32);for(d=0;d<e.length;d++)h=b.getInt32(c+8*d,this._LITTLE_ENDIAN),m=b.getInt32(c+4+8*d,this._LITTLE_ENDIAN),0>m?(m=~m,h=~h,h+=1,h>=Math.pow(2,32)&&(h=0,m+=1),g[d]=-(m*n+h)):g[d]=m*n+h,(g[d]>Number.MAX_SAFE_INTEGER||g[d]<Number.MIN_SAFE_INTEGER)&&console.error(g[d]+"\u8d85\u51faJS\u957f\u6574\u578b\u5b89\u5168\u8303\u56f4\uff0c\u7cbe\u5ea6\u5c06\u4e0d\u51c6\u786e\uff0c\u8bf7\u68c0\u67e5\u4e1a\u52a1\u6570\u636e");f[a]=g;c+=8*e.length}else if("STRUCT"==e.type){if(!this._dataStruct[e.structName])return console.warn("message definitions not found:"+
e.structName),null;m=b.buffer;h=this._GetBodyLen(this._dataStruct[e.structName]);k&&0<c%h.maxBaseDataLen&&(c+=h.maxBaseDataLen-c%h.maxBaseDataLen);m=new DataView(m,c+b.byteOffset,h.len);m=this._ParseBody(this._dataStruct[e.structName],m);f[a]=m;c+=h.len}else if("STRUCT_ARRAY"==e.type){if(!this._dataStruct[e.structName])return console.warn("message definitions not found:"+e.structName),null;h=this._GetBodyLen(this._dataStruct[e.structName]);k&&0<c%h.maxBaseDataLen&&(c+=h.maxBaseDataLen-c%h.maxBaseDataLen);
g=[];for(d=0;d<e.length;d++)m=b.buffer,m=new DataView(m,c+b.byteOffset,h.len),m=this._ParseBody(this._dataStruct[e.structName],m),g[d]=m,c+=h.len;f[a]=g}}return f};
MessageDecoder.prototype.serialize=function(l){if(!this._dataStruct)return console.error("message definitions not found"),null;if(!this._dataStruct[l.cmdType])return console.error("message:"+l.cmdType+" definitions not found"),null;var b=this._dataStruct[l.cmdType].req;if(!b)return console.warn("message req definition not found:"+l.cmdType),null;var c=this._GenHeader(l.cmdType);c=new DataView(c);var f=0,k=null;b&&l.data&&(l=this._GenBody(b,l.data))&&(k=new DataView(l),f=k.byteLength);l=new ArrayBuffer(this._MSG_HEADER_LEN+
f);b=new DataView(l);for(var a=0;a<this._MSG_HEADER_LEN;a++)b.setUint8(a,c.getUint8(a));for(a=0;a<f;a++)b.setUint8(a+this._MSG_HEADER_LEN,k.getUint8(a));if(DEBUG){c="";for(a=0;a<b.byteLength;a++)c+=b.getUint8(a).toString(16)+" ";console.log("\u52a0\u5bc6\u524d:"+c)}l=this._SPEncrypt2_0_Encrypt(l);if(DEBUG){c="";for(a=0;a<b.byteLength;a++)c+=b.getUint8(a).toString(16)+" ";console.log("\u52a0\u5bc6\u540e:"+c)}return l};
MessageDecoder.prototype.deserialize=function(l){if(!this._dataStruct)return console.error("message definitions not found"),null;if(!l)return console.error("buffer is "+l),null;if(DEBUG){for(var b="",c=new DataView(l),f=0;f<c.byteLength;f++)b+=c.getUint8(f).toString(16)+" ";console.log("\u89e3\u5bc6\u524d:"+b)}this._SPEncrypt2_0_Decode(l);if(DEBUG){b="";c=new DataView(l);for(f=0;f<c.byteLength;f++)b+=c.getUint8(f).toString(16)+" ";console.log("\u89e3\u5bc6\u540e:"+b)}f=new DataView(l);f.getUint8(0);
f.getUint8(1);b="0x"+f.getUint16(2,this._LITTLE_ENDIAN).toString(16);if(!this._dataStruct[b])return console.warn("message definition not found:"+b),null;c=this._dataStruct[b].resp;if(!c)return console.warn("message resp definition not found:"+b),null;var k={},a=[];if(4<l.byteLength){new DataView(l,4,l.byteLength-4);var e=this._GetBodyLen(c);if(0==(l.byteLength-4)%e.len){var g=(l.byteLength-4)/e.len;for(f=0;f<g;f++){var h=new DataView(l,4+e.len*f,e.len);a[f]=this._ParseBody(c,h)}}else console.error("\u8fd4\u56de\u62a5\u6587\u957f\u5ea6\u975e\u6574\u6570\u500d");
k.datas=a}k.cmdType=b;return k};MessageDecoder.prototype.getHeartBeatMsg=function(){return{cmdType:this._heartBeatCode}};var DBTMsgDecoder={getDecoder:function(l){return new MessageDecoder(l)}};module.exports=DBTMsgDecoder;